<?php

namespace EDP;

class Message
{
    public function getMenu()
    {
        return "1) PIEROGI RUSKIE OKRASZONE SMAŻONYM BOCZKIEM I CEBULKĄ, SURÓWKA
2) GULASZ WIEPRZOWY Z PYZAMI ZIEMNIACZANYMI, SURÓWKA (BURACZKI)
3) FILECIKI DROBIOWE W ŚMIETANOWYM SOSIE Z SUSZONYMI POMIDORAMI, POREM I SZPARAGAMI, MAKARON, SAŁATA Z POMIDOREM I SOSEM BALSAMICZNYM
4) PULPECIKI W POMIDOROWYM SOSIE Z DODATKIEM WŁOSKICH ZIÓŁ, CZOSNKU, MARCHEWKI I GROSZKU, ZIEMNIAKI, SURÓWKA";
    }
}
